---
# defaults file for k3d_dev_cluster
k3d_cluster_name: "default-dev-cluster"
k3d_version: 5.4.6
k3d_need_to_install: False

k3d_install_dir: /usr/local/bin
k3d_binary_name: "k3d"

k3d_cmd: "k3d"

k3d_args_create_cluster: ["cluster", "create", "--kubeconfig-update-default=false"]
k3d_args_list_clusters: ["cluster", "list", "-o", "json"]
k3d_args_write_kubeconfig: ["kubeconfig", "write"]

k3d_ingress_http_port: 80
k3d_ingress_https_port: 443
k3d_ingress_exposed: True

local_kubeconfig_path:  "/tmp/{{ k3d_cluster_name }}-kubeconfig"


k3d_delete_all_clusters: False
k3d_delete_cluster: False

k3d_builtin_manifest_dir: ""

####
k3d_image: rancher/k3s:v1.20.4-k3s1
k3d_api_server_port: 6443
k3d_kubeconfig_update_default: false
k3d_kubeconfig_switch_current_context: false
k3d_servers: 1
k3d_agent: 0
k3d_ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer

  - port: 443:443
    nodeFilters:
      - loadbalancer

